name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ ADD IT HERE (right after checkout)
      - name: Create .env file
        run: |
          echo "PG_USER=${{ secrets.PG_USER }}" >> .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "PG_DB=${{ secrets.PG_DB }}" >> .env
          echo "PG_PORT=${{ secrets.PG_PORT }}" >> .env
          echo "PG_HOST=db" >> .env
          echo "JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}" >> .env

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      # ❗ REMOVE env: block (not needed anymore)
      - name: Start containers
        run: |
          docker compose up -d --build
          sleep 5

      - name: Show logs if crash happens
        run: docker compose logs

      - name: Run migrations
        run: docker exec flask_app flask db upgrade
        
      - name: Run tests properly
        run: docker exec  flask_app pytest